/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marcos_vinicius_almeida_pipeline;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class GUIpipeline extends javax.swing.JFrame {

    /**
     * Creates new form GUIpipeline
     */
    public GUIpipeline() {
        initComponents();
        setSize(1120, 518);  // Exemplo de tamanho, ajuste conforme necessário
    
        // Centraliza a janela na tela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hiText = new javax.swing.JTextField();
        loText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jButton1.setText("NEXT STEP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(494, 421, 111, 25);

        jTable1.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IF", "ID", "EXE", "MEM", "WB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(311, 143, 484, 260);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PC");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 80, 17);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLOCK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 80, 17);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEMÓRIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(171, 143, 101, 270);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INSTRUÇÕES"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(28, 143, 101, 270);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REGISTRADOR 16:31"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(966, 143, 143, 288);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INSTRUÇÃO  BIN:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 100, 150, 17);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "REGISTRADOR 0:15"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(813, 143, 147, 288);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(70, 70, 64, 23);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(440, 100, 320, 23);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(70, 30, 64, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "exemplo", "avaliacao", "avaliacao2" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(440, 60, 140, 23);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ARQUIVO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 60, 70, 17);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(860, 70, 42, 17);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HI:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(860, 40, 18, 17);
        getContentPane().add(hiText);
        hiText.setBounds(890, 40, 80, 23);
        getContentPane().add(loText);
        loText.setBounds(890, 70, 80, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marcos_vinicius_almeida_pipeline/imagens/troll.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1120, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String arquivo = (String)jComboBox1.getSelectedItem();
        Main.executePipeline(arquivo);
        DefaultTableModel dtmCanais = (DefaultTableModel) jTable1.getModel();
        String[] canalInterface = Main.retornaCanais();
        dtmCanais.addRow(canalInterface);
        DefaultTableModel dtmMemoria = (DefaultTableModel) jTable2.getModel();
        int[] memoria = Main.retornaMemoria();
        dtmMemoria.setRowCount(0);
        for(int i = 0; i < memoria.length;i++){
            Object[] rowData = {memoria[i]};
            dtmMemoria.addRow(rowData);
        }
        DefaultTableModel dtmInstrucoes = (DefaultTableModel) jTable3.getModel();
        String[] instrucoes = Main.retornaInstrucoes();
        dtmInstrucoes.setRowCount(0);
        for(int i = 0; i < instrucoes.length;i++){
            Object[] rowData = {instrucoes[i]};
            dtmInstrucoes.addRow(rowData);
        }
        DefaultTableModel dtmReg15 = (DefaultTableModel) jTable5.getModel();
        int[] reg15 = Main.retornaReg15();
        dtmReg15.setRowCount(0);
        for(int i = 0; i < reg15.length;i++){
            Object[] rowData = {reg15[i]};
            dtmReg15.addRow(rowData);
        }
        DefaultTableModel dtmReg31 = (DefaultTableModel) jTable4.getModel();
        int[] reg31 = Main.retornaReg31();
        dtmReg31.setRowCount(0);
        for(int i = 0; i < reg31.length;i++){
            Object[] rowData = {reg31[i]};
            dtmReg31.addRow(rowData);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIpipeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIpipeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIpipeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIpipeline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIpipeline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField hiText;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    public static javax.swing.JTextField loText;
    // End of variables declaration//GEN-END:variables
}
